kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: nginx

spec:           # go google and search kubernets pods
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
