apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx  # ✅ lowercase 'namespace'
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
  
